### PR TITLE
Website redesign

### PR DESCRIPTION
**Pull request by thgeorgiou**
I created a small redesign of the project website to make it look cleaner. Feel free to use it if you like it!

I removed CNAME from my repository because it was causing problems so you should probably add it back if you decide to use this. Also the Paypal Donate/Facebook/G+ buttons and GA are missing since I didn't want to mess with your data.

### CODE REVIEW

**Comment by thgeorgiou** [comment]
You can check the new design over here: http://sakisds.github.io/apkshellext

**Comment by kkguo** [comment]
@sakisds , it's cool, I love it. Thanks for the help. 
So do you want to take the control of the site :smile: ? As I'm not good at Web at all...
Here is a more rude request:,
- (optional) Can you make it a jekyll? So I have a blog page, and also I can just change the version number in one place every time for release. (currently I'm manually changing the link to download every times, and also I need to change the latest file to make sure the program detects an update). 
- Can you make the background more eye friendly? (It's OK if you insists to keep, actually I don't have any color sense)
- You forget to mention your name on the page :)
- Your suggestion?

**Comment by sylveon** [comment]
Using the [Polymer](https://www.polymer-project.org/1.0/) javascript library could add a material design-like apparence

**Comment by kkguo** [comment]
Any tech is good to me, but I prefer left it to pros :smiley:

**Comment by thgeorgiou** [comment]
@charlesmilette Since the page doesn't have anything that's active, we could just style the elements to look like material without using JS if @kkguo prefers that look.

@kkguo Unfortunately, I don't know how to write Jekyll templates so that would take a while. :/
About the background colours, you mean reverse it (white text on dark background) or just tweak the colours? I agree the grey on the top is not that good.

**Comment by kkguo** [comment]
I mean the color,  it's a bit sharp. My favorite is green,  as android is
green, what do you think? Again, you are making it, so it's your call.

**Comment by thgeorgiou** [comment]
I will check if I can work some green in. :smile:

**Comment by sylveon** [comment]
@sakisds Polymer is an library that add elements to html elements. ex: paper-button is an element like button, but styled to fit material design.

**Comment by thgeorgiou** [comment]
@kkguo I updated the website to a more "material" look, you can check it out over [here](http://sakisds.github.io/apkshellext/).

**Comment by kkguo** [comment]
thanks, i will merge it
btw, can you put one icon for each section? And also FYI, @Vince has made a new logo under [Resources](https://github.com/kkguo/apkshellext/tree/ApkShellext2/ApkShellext2/Resources/Apkshellext_icons) of the source tree,

**Comment by kkguo** [comment]
@sakisds, thanks for update, I have add you as Collaborator, I think you can push change to the repository now.

**Comment by kkguo** [comment]
@sakisds , do you have a telegram account? so we can talk instantly :)

**Comment by thgeorgiou** [comment]
@kkguo I have an account, same username as here (@sakisds)!

**Pull request merged**
